---
pagetitle: "fairenoughTEST"
format: html
---

# fairenough's pipeline

```{r}
devtools::install_github("openwashdata/fairenough")
```

```{r}
chat <- ellmer::chat_openai(model = "gpt-4.1-nano",api_args = list(temperature=0.3))

Nicolo <- list(given = "Nicolo", 
               family = "Massari", 
               roles = c("aut", "cre"),  
               email = "nmassari@ethz.ch", 
               orcid = "0009-0006-8421-930X",
               affiliation="ETH Zurich")
Lars <- list(given = "Lars", 
             family = "Schöbitz", 
             roles = c("aut", "ctb"), 
             email = "lschoebitz@ethz.ch", 
             orcid = "0000-0003-2196-5015", 
             affiliation="ETH Zurich")
Liz <- list(given = "Elizabeth", 
            family = "Tilley", 
            roles = c("aut", "fnd"), 
            email = "tilleye@ethz.ch", 
            orcid = "0000-0002-2095-9724", 
            affiliation="ETH Zurich")

fairenough::fairenough(chat, 
                pkg_name = "palmerpenguins",
                title = "Palmer Penguins",
                description = "The Palmer Penguins dataset contains penguins measurements.",
                github_user = "Global-Health-Engineering",
                authors = list(Nicolo, Lars, Liz),
                license =  "CC-BY-4.0",
                overwrite = TRUE)
```